name: Bug report
description: File a bug report
body:
  - type: input
    id: version
    attributes:
      label: Version of Hardhat
      description: Run `npx hardhat version` to get the version of Hardhat that you are using
      placeholder: 1.2.3
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: search-terms
    attributes:
      label: Search terms
      description: Include the search terms you used before opening this issue. This will help others find your issue.
