name: Issue/PR autoassignment

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: "Autoassign issue/PR"
        if: ${{ !contains(fromJson('["alcuadrado"]'), github.event.issue.user.login || github.event.pull_request.user.login) }}
        uses: fvictorio/auto-assign-issue@ebd37fbe5cd7d1dbd0a3e4136d0ad0aa7f5a24e0
        with:
          assignees: alcuadrado
          numOfAssignee: 1
