name: Issue/PR autoassignment

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: "Autoassign issue/PR"
        if: ${{ !contains(fromJson('["alcuadrado","fvictorio"]'), github.event.issue.user.login || github.event.pull_request.user.login) }}
        uses: pozil/auto-assign-issue@v1.3.0
        with:
          assignees: alcuadrado,fvictorio
          numOfAssignee: 1
