name: Issue/PR autoassignment

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: "Autoassign issue/PR"
        if: ${{ !contains(fromJson('["fvictorio"]'), github.event.issue.user.login || github.event.pull_request.user.login) }}
        uses: fvictorio/auto-assign-issue@cde4cd1c9da465655f117add2f0d9c2a4377e366

        with:
          assignees: fvictorio
          numOfAssignee: 1
