name: Add label to new issue

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created, edited]

jobs:
  label-new-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const run = require("../scripts/script.js");
            await run({ github, context })
