name: Add label to new issue

on:
  push:
    branches:
      - **

jobs:
  label-new-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        run: |
          chmod +x test.sh
          ./test.sh
        shell:
          bash
