name: Check if PR has changeset

on:
  pull_request:
    branches:
      - "**"

jobs:
  check-if-changeset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const pullNumber = context.issue.number;

            const { data: files } = await github.rest.pulls.listFiles({
              ...context.issue,
              pull_number: pullNumber
            });

            const changeset = files.find(
              file => file.status === "added" && file.filename.startsWith(".changeset/")
            );

            if (changeset !== undefined) {
              console.log("Changeset found:", changeset.filename);
              return;
            }

            const { data: pull } = await github.rest.pulls.get({
              ...context.issue,
              pull_number: pullNumber
            });

            console.log(pull.body)

            const noChangesetNeededComment = pull.body
              ?.toLowerCase()
              .includes("no changeset needed");

            if (noChangesetNeededComment) {
              console.log("The PR description says that no changeset is needed");
              return;
            }

            console.error("No changeset found");
            process.exit(1);
