name: Label new issues

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const issue = await github.rest.issues.get({
              owner: context.issue.owner,
              repo: context.issue.repo,
              issue_number: context.issue.number
            });

            const hasStatus = issue.data.labels.some(({ name }) =>
              name.startsWith("status:")
            );

            if (!hasStatus) {
              await github.rest.issues.addLabels({
                owner: context.issue.owner,
                repo: context.issue.repo,
                issue_number: context.issue.number,
                labels: [{ name: "status:triaging" }]
              });
